#!/bin/bash -e
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ -z $1 ]; then
	echo "Usage: $0 config.env" >&2
	exit 1
fi

set -a
. "$dir/$1"
set +a

rm -rf package
mkdir package

cp -R node_modules package/
cp *.js package/
cp -R config package/

mkdir package/pdftools
cp pdftools/pdftotext-linux-x86_64 package/pdftools/
cp -R pdftools/poppler-data package/pdftools/

# Cut over 100 MB of redundant files
rm -rf package/node_modules/cld/deps

j2 "$dir/lambda_template.yaml.j2" > "$dir/package/template.yaml"

sam package --template-file "$dir/package/template.yaml" --s3-bucket $deployment_bucket_name --output-template-file "$dir/package/package.yaml"
aws cloudformation deploy --template-file "$dir/package/package.yaml" --stack-name $stack_name --capabilities CAPABILITY_IAM
rm -rf "$dir/package"
