#!/bin/bash

PDF_TOOLS_VERSION="0.0.3"
PDF_TOOLS_URL="https://zotero-download.s3.amazonaws.com/pdftools/pdftools-$PDF_TOOLS_VERSION.tar.gz"

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $SCRIPT_DIR

rm -rf pdftools
mkdir pdftools
cd pdftools

curl -o pdftools.tar.gz $PDF_TOOLS_URL
tar -zxvf pdftools.tar.gz
rm pdftools.tar.gz

echo Done
